name: PROD Workflow
on:
  push:
    branches:
      - main
jobs:
  all:
    name: All actions
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "glebbars"
          git config user.email "glebars2004@gmail.com"

      - name: Setup npm
        run: npm install
        timeout-minutes: 5

      - name: Lint source code
        run: npx nx affected --target=lint --parallel=3 --base=last-release
        timeout-minutes: 5

      - name: Test source code
        run: npx nx affected --target=test --parallel=3 --base=last-release
        timeout-minutes: 5

      - name: Bump versions and generate changelogs
        run: npx nx affected --target=version --parallel=1 --base=last-release
        timeout-minutes: 10

      - name: Generate .npmrc file
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}" > .npmrc

      - name: Publishing packages
        run: npx nx affected --target=release
        timeout-minutes: 10

      - name: Tag last-release
        run: |
          git push --follow-tags
          git tag -f last-release
          git push origin last-release --force
